### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by Daniel22L** [linhaojia13/PointMetaBase#10]
Details:
```
- Ubuntu 22.04.2 TLS
- Conda 23.1.0
- CUDA 12.0
- gcc 11.3.0
```

I have followed the installation instructions, modifying in the installation.sh this:
```
module load cuda/11.3.1
```
For:
```
module load cuda/12.0 #module load cuda/11.3.1
```
It works, but with the following errors:
```
ERROR: Unable to locate a modulefile for 'cuda/12.0'
ERROR: Unable to locate a modulefile for 'gcc/7.5.0'
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```
Errors with module I think are not a problem. From what I've read they are no longer used in this version of ubuntu.

About the problem with cuda:
```
torch.cuda.is_cuda_available()
True
```

However, when running:
```
CUDA_VISIBLE_DEVICES=0 bash script/main_segmentation.sh cfgs/s3dis/pointmetabase-l.yaml wandb.use_wandb=False                                                    
```
I get:
```
script/main_segmentation.sh: line 31: nvcc: command not found
lupus-fon.mines-paristech.local
1
Traceback (most recent call last):
  File "examples/segmentation/main.py", line 15, in <module>
    from openpoints.utils import set_random_seed, save_checkpoint, load_checkpoint, resume_checkpoint, setup_logger_dist, \
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/__init__.py", line 1, in <module>
    from .transforms import *
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/transforms/__init__.py", line 5, in <module>
    from .transforms_factory import * 
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/transforms/transforms_factory.py", line 2, in <module>
    from ..utils.registry import Registry
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/utils/__init__.py", line 3, in <module>
    from .logger import setup_logger_dist, generate_exp_directory, resume_exp_directory
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/utils/logger.py", line 9, in <module>
    import shortuuid
ModuleNotFoundError: No module named 'shortuuid'
```

# First modification
So I have modified in the installation.sh this:
```
conda install -y pytorch=1.10.1 torchvision cudatoolkit=11.3 -c pytorch -c nvidia
```
For:
```
conda install -c "nvidia/label/cuda-11.3.1" cuda-toolkit
conda install -y pytorch=1.10.1 torchvision cudatoolkit=11.3 -c pytorch
```

And a get during the installation:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    'build_ext': BuildExtension
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 735, in build_extensions
    build_ext.build_extensions(self)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 565, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1404, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/dlamasnovoa/miniconda3/envs/openpoints/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

# Second modification
So I have modified in the installation.sh this:
```
conda install -y pytorch=1.10.1 torchvision cudatoolkit=11.3 -c pytorch -c nvidia
```
For:
```
 conda install -c nvidia cuda-toolkit
conda install -y pytorch=1.10.1 torchvision cudatoolkit=11.3 -c pytorch
```

And a get:
```
RuntimeError: 
The detected CUDA version (12.1) mismatches the version that was used to compile
PyTorch (11.3). Please make sure to use the same CUDA version
```
However:
```
torch.cuda.is_cuda_available()
True
```

But when running:
```
CUDA_VISIBLE_DEVICES=0 bash script/main_segmentation.sh cfgs/s3dis/pointmetabase-l.yaml wandb.use_wandb=False                                                    
```
I get:
```
Traceback (most recent call last):
  File "examples/segmentation/main.py", line 15, in <module>
    from openpoints.utils import set_random_seed, save_checkpoint, load_checkpoint, resume_checkpoint, setup_logger_dist, \
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/__init__.py", line 1, in <module>
    from .transforms import *
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/transforms/__init__.py", line 5, in <module>
    from .transforms_factory import * 
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/transforms/transforms_factory.py", line 2, in <module>
    from ..utils.registry import Registry
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/utils/__init__.py", line 3, in <module>
    from .logger import setup_logger_dist, generate_exp_directory, resume_exp_directory
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/utils/logger.py", line 9, in <module>
    import shortuuid
ModuleNotFoundError: No module named 'shortuuid'
```

Doing:
```
pip install shortuuid
```
When runing:
```
CUDA_VISIBLE_DEVICES=0 bash script/main_segmentation.sh cfgs/s3dis/pointmetabase-l.yaml wandb.use_wandb=False                                                    
```
I get:
```
Traceback (most recent call last):
  File "examples/segmentation/main.py", line 18, in <module>
    from openpoints.dataset import build_dataloader_from_cfg, get_features_by_keys, get_class_weights
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/dataset/__init__.py", line 8, in <module>
    from .scanobjectnn import * # comment for chamfer error
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/dataset/scanobjectnn/__init__.py", line 1, in <module>
    from .scanobjectnn import ScanObjectNNHardest
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/dataset/scanobjectnn/scanobjectnn.py", line 5, in <module>
    from openpoints.models.layers import fps
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/models/__init__.py", line 6, in <module>
    from .backbone import *
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/models/backbone/__init__.py", line 2, in <module>
    from .pointnetv2 import PointNet2Encoder, PointNet2Decoder, PointNetFPModule
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/models/backbone/pointnetv2.py", line 14, in <module>
    from ..layers import furthest_point_sample, random_sample,  LocalAggregation, three_interpolation, create_convblock1d # grid_subsampling,
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/models/layers/__init__.py", line 9, in <module>
    from .group_embed import SubsampleGroup, PointPatchEmbed
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/models/layers/group_embed.py", line 6, in <module>
    from .subsample import furthest_point_sample, random_sample
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/models/layers/subsample.py", line 8, in <module>
    from openpoints.cpp.pointnet2_batch import pointnet2_cuda
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/cpp/__init__.py", line 6, in <module>
    from .pointnet2_batch import pointnet2_cuda
  File "/home/dlamasnovoa/Documents/repositories/PointMetaBase/examples/segmentation/../../openpoints/cpp/pointnet2_batch/__init__.py", line 2, in <module>
    import pointnet2_batch_cuda as pointnet2_cuda
ModuleNotFoundError: No module named 'pointnet2_batch_cuda'
```

**Comment by SONGQIHAI** [comment]
Hello, I have encountered the same issue as you regarding ‘pointnet2_ batch_cuda‘, Have you resolved the issue with the module now?

**Comment by Daniel22L** [comment]
I decided to use docker to solve it.

Docker image: pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel

Install in the container this in a .sh:

```
# python, pytorch and cuda already installed in docker image
# activate environment
conda activate

# install relevant packages
# torch-scatter is a must, and others are optional
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.1+cu113.html
# pip install torch-scatter torch-sparse torch-cluster torch-geometric -f https://data.pyg.org/whl/torch-1.10.1+cu113.html
pip install -r requirements.txt

# install cpp extensions, the pointnet++ library
cd openpoints/cpp/pointnet2_batch
python setup.py install
cd ../

# grid_subsampling library. necessary only if interested in S3DIS_sphere
cd subsampling
python setup.py build_ext --inplace
cd ..


# # point transformer library. Necessary only if interested in Point Transformer and Stratified Transformer
cd pointops/
python setup.py install
cd ..


# Blow are functions that optional. Necessary only if interested in reconstruction tasks such as completion
cd chamfer_dist
python setup.py install --user
cd ../emd
python setup.py install --user
cd ../../../
```


Being the requirements:
```
scikit-learn==1.0.2
pickleshare==0.7.5
ninja==1.10.2.3
gdown==4.7.1 # The version was not specified
easydict==1.9
PyYAML==6.0
protobuf==3.19.4
tensorboard==2.8.0
termcolor==1.1.0
tqdm==4.62.3
multimethod==1.7
h5py==3.6.0
matplotlib==3.5.1
wandb==0.15.2 # The version was not specified
pyvista==0.33.2
setuptools==59.5.0
Cython==0.29.28
pandas==1.3.5 # The version was not specified
shortuuid==1.0.11 # It was not in the original requirements.txt but it was needed when executing

# for docs
mkdocs-material==9.1.11 # The version was not specified
mkdocs-awesome-pages-plugin==2.9.1 # The version was not specified
mdx_truly_sane_lists==1.3 # The version was not specified
```
