### ISSUE TITLE
FileNotFoundError: S3DIS: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ywang864** [linhaojia13/PointMetaBase#20]
When I follow your Readme and train with S3DIS, this is the error I got, pretty sure the data is already prepared as PointNeXt, do you have ant idea how to resolve this？

> Traceback (most recent call last):
>   File "/mnt/d/PointMetaBase/examples/segmentation/../../openpoints/utils/registry.py", line 291, in build_from_cfg
>     return obj_cls(**obj_cfg)
>   File "/mnt/d/PointMetaBase/examples/segmentation/../../openpoints/dataset/s3dis/s3dis.py", line 80, in __init__
>     data_list = sorted(os.listdir(raw_root))
> FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/MEMORY_DATA/s3disfull/raw'   
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "examples/segmentation/main.py", line 737, in <module>
>     main(0, cfg)
>   File "examples/segmentation/main.py", line 154, in main
>     val_loader = build_dataloader_from_cfg(cfg.get('val_batch_size', cfg.batch_size),
>   File "/mnt/d/PointMetaBase/examples/segmentation/../../openpoints/dataset/build.py", line 71, in build_dataloader_from_cfg
>     dataset = build_dataset_from_cfg(dataset_cfg.common, split_cfg)
>   File "/mnt/d/PointMetaBase/examples/segmentation/../../openpoints/dataset/build.py", line 38, in build_dataset_from_cfg
>     return DATASETS.build(cfg, default_args=default_args)
>   File "/mnt/d/PointMetaBase/examples/segmentation/../../openpoints/utils/registry.py", line 149, in build
>     return self.build_func(*args, **kwargs, registry=self)
>   File "/mnt/d/PointMetaBase/examples/segmentation/../../openpoints/utils/registry.py", line 294, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> FileNotFoundError: S3DIS: [Errno 2] No such file or directory: '/dev/shm/MEMORY_DATA/s3disfull/raw'

**Comment by WeijiaChen123** [comment]
I also had got this error, you can look for a file in cfgs/s3dis named default.yaml, replace /dev/shm/MEMORY_DATA/s3disfull with your data's path. This error will be solved.
