### ISSUE TITLE
CUDA_VISIBLE_DEVICES=0 bash script/main_segmentation.sh cfgs/s3dis/pointmetabase-l.yaml 

### ISSUE THREAD

**Issue by yurayurateikoku1** [linhaojia13/PointMetaBase#9]
Traceback (most recent call last):
  File "/root/PointMetaBase/examples/segmentation/../../openpoints/utils/registry.py", line 291, in build_from_cfg
    return obj_cls(**obj_cfg)
  File "/root/PointMetaBase/examples/segmentation/../../openpoints/dataset/s3dis/s3dis.py", line 80, in __init__
    data_list = sorted(os.listdir(raw_root))
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/MEMORY_DATA/s3disfull/raw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/segmentation/main.py", line 737, in <module>
    main(0, cfg)
  File "examples/segmentation/main.py", line 159, in main
    distributed=cfg.distributed
  File "/root/PointMetaBase/examples/segmentation/../../openpoints/dataset/build.py", line 71, in build_dataloader_from_cfg
    dataset = build_dataset_from_cfg(dataset_cfg.common, split_cfg)
  File "/root/PointMetaBase/examples/segmentation/../../openpoints/dataset/build.py", line 38, in build_dataset_from_cfg
    return DATASETS.build(cfg, default_args=default_args)
  File "/root/PointMetaBase/examples/segmentation/../../openpoints/utils/registry.py", line 149, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/root/PointMetaBase/examples/segmentation/../../openpoints/utils/registry.py", line 294, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: S3DIS: [Errno 2] No such file or directory: '/dev/shm/MEMORY_DATA/s3disfull/raw'

**Comment by ywang864** [comment]
Hi, I am facing the same issue here, how did you solve it?
